### ISSUE TITLE
VNCserver 启动失败

### ISSUE THREAD

**Issue by jiz4oh** [tom-snow/docker-ComWechat#4]
<img width="756" alt="image" src="https://user-images.githubusercontent.com/41264693/219938567-b9a02b0b-e380-427a-872b-14bf3d7e1e9c.png">

按照 https://blog.honus.top/2022/10/15/580.html 配置，使用 `docker-compose up -d` 启动 docker 之后调用 `docker logs comwechat` 报如上错误。

具体的 `docker-compose.yaml` 文件如下

```yaml
version: '3.3'
services:
    wechatpchook:
        container_name: comwechat
        environment:
            - VNCPASS=admin123
            - COMWECHAT=https://github.com/ljc545w/ComWeChatRobot/releases/download/3.7.0.30-0.1.0-pre/3.7.0.30-0.1.0-pre.zip
        volumes:
            - "/root/WeChat/Files/:/home/user/.wine/drive_c/users/user/My Documents/WeChat Files/"
            - "/root/WeChat/Data/:/home/user/.wine/drive_c/users/user/Application Data/"
        privileged: true
        network_mode: host
        image: tomsnow1999/docker-com_wechat_robot:latest
```
